### ISSUE TITLE
npm install - fatal error: bluetooth/bluetooth.h: No such file or directory

### ISSUE THREAD

**Issue by eguo** [IBM-Bluemix/iot-sensor-tag#1]
Can some help me with this problem:

I have following error when I run npm install inside /iot-sensor-tag/publish folder.

"...Release/obj.target/hci-ble/src/hci-ble.o
../src/hci-ble.c:9:33: fatal error: bluetooth/bluetooth.h: No such file or directory
compilation terminated.
make: **\* [Release/obj.target/hci-ble/src/hci-ble.o] Error 1
make: Leaving directory..."

This is in a Galaxy S4 Active Android phone running debian linux.  

See complete output here:

root@localhost:/opt/konectera/gitwork/iot-sensor-tag/publish# npm install
npm WARN package.json @ No repository field.
/

> noble@0.3.5 install /opt/konectera/gitwork/iot-sensor-tag/publish/node_modules/sensortag/node_modules/noble
> node install.js

noble install: platform is "linux'
noble install: running node-gyp ...
make: Entering directory '/opt/konectera/gitwork/iot-sensor-tag/publish/node_modules/sensortag/node_modules/noble/build'
  CC(target) Release/obj.target/hci-ble/src/hci-ble.o
../src/hci-ble.c:9:33: fatal error: bluetooth/bluetooth.h: No such file or directory
 #include <bluetooth/bluetooth.h>
                                 ^
compilation terminated.
hci-ble.target.mk:78: recipe for target 'Release/obj.target/hci-ble/src/hci-ble.o' failed
make: **\* [Release/obj.target/hci-ble/src/hci-ble.o] Error 1
make: Leaving directory '/opt/konectera/gitwork/iot-sensor-tag/publish/node_modules/sensortag/node_modules/noble/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.4.0-1429916
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /opt/konectera/gitwork/iot-sensor-tag/publish/node_modules/sensortag/node_modules/noble
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
noble install: done

npm ERR! noble@0.3.5 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the noble@0.3.5 install script.
npm ERR! This is most likely a problem with the noble package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls noble
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.4.0-1429916
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /opt/konectera/gitwork/iot-sensor-tag/publish
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by belun** [comment]
i had this problem when installing cylon-ble which needed noble, which required  libbluetooth-dev. how was i supposed to find out about that depedency.

npm install noble    was just failing

**Comment by ryanjbaxter** [comment]
@belun as mentioned above it is mentioned in the README in the publish directory

**Comment by belun** [comment]
@ryanjbaxter i did not mean to appear stupid, on purpose
indeed, it is mentioned here:  https://www.npmjs.com/package/noble
it is just that, i thought, you do "npm install something", and npm it takes care of the dependencies

**Comment by ryanjbaxter** [comment]
@belun the problem is that libbluetooth-dev is not a node module it is an OS level dependency so npm install cannot install it.
