### ISSUE TITLE
npm istallation failure

### ISSUE THREAD

**Issue by HarrySaggu11** [IBM-Bluemix/iot-sensor-tag#4]
I am using a Beagle Bone Rev C and Ti sensor tag  CC2650. As per your tutorial @ryanjbaxter I followed the whole procedure step by step but failed to connect the sensor tag as the screen showed npm install failed. I am using Windows 7 and used Putty to access the beagle Bone. I have tried doing the same thing on two different internet sources, First at the University and Second at my home. There different reason npm installation failure. please find the attachments for more information. 
![issue with ceritifcation](https://cloud.githubusercontent.com/assets/13432864/8797960/ec0e3a46-2f96-11e5-9a41-62a9d69942a6.jpg)

![npm installation issue](https://cloud.githubusercontent.com/assets/13432864/8797975/009a3e92-2f97-11e5-9676-8a608c544a07.jpg)

Please advise me as to what shall I do in order to get this problem fixed. ?

**Comment by ryanjbaxter** [comment]
@HarrySaggu11 the second screen shot appears to be from a different project, there is no setup.sh file in this repository.  

The error in the first screenshot looks like an SSL problem.  I found this [issue](https://github.com/npm/npm/issues/2902) in the NPM repository.  You might want to check that the system clock on your beaglebone is set to the correct time.  Let me know if that fixes it.

**Comment by HarrySaggu11** [comment]
hey @ryanjbaxter how can I set the time on Beaglebone ?

**Comment by ryanjbaxter** [comment]
@HarrySaggu11 Google is your friend :)  I have never had to do it myself.  A quick search and it looks like this page might be useful http://derekmolloy.ie/automatically-setting-the-beaglebone-black-time-using-ntp/

**Comment by HarrySaggu11** [comment]
hey @ryanjbaxter,
Thanks for your reply, I'll try to use the link right away.

I did the same thing without a beagle bone and used sensor tag's mobile app instead of beagle bone for pushing data on the cloud. Now i am stuck in Bluemix. 
The problem is that I cannot generate the graphs on Hadoop, IBM's analytic's tool for Big data. I can t even access the data from cloudant on dash DB. On hadoop, it constantly keeps requesting for data and on dash db, under the message section its shows 'Request Queued'.
I reckon the the data from cloudant is not getting send to either of dash db and hadoop for further processing. 
Please have a look at the attachments and kindly advise as to what should i do ?

![cloudant issue 1](https://cloud.githubusercontent.com/assets/13432864/8826246/fe8f0f9c-307c-11e5-80f3-5e648e107bb9.jpg)
![cloudant issue 2](https://cloud.githubusercontent.com/assets/13432864/8826251/05987bb6-307d-11e5-8852-5f6ae2933cf3.jpg)

Many Thanks

**Comment by ryanjbaxter** [comment]
@HarrySaggu11 please only post issues related to the code in the repo here.  If you have general questions about Bluemix and its services please post them to either developerWorks or StackOverflow.  See the link here https://developer.ibm.com/bluemix/#support

**Comment by HarrySaggu11** [comment]
thanks @ryanjbaxter
