### ISSUE TITLE
update video

### ISSUE THREAD

**Issue by MariusHerget** [IBM-Bluemix/iot-sensor-tag#8]
Hey guys, how about to insert the update video too? https://www.youtube.com/watch?v=lZuq85EJGWo

**Comment by ryanjbaxter** [comment]
can u be more specific about what u want to do with the video?

**Comment by MariusHerget** [comment]
you linked only your first version of the video :)
"Some of the content in this video may be outdated, you can check out an updated video at http://youtu.be/lZuq85EJGWo."

it would be nice to directly link the updated video here in GitHub too. Therefore you see all videos at once

**Comment by ryanjbaxter** [comment]
The updated video is linked to by clicking the first image in the README

**Comment by MariusHerget** [comment]
oh sorry my fault. Didnt recognize this was more than a image.

btw: great work - will use it as my basic for my IoT showcase :)

**Comment by ryanjbaxter** [comment]
NP
